// Code generated by protoc-gen-go. DO NOT EDIT.
// source: marabunta.proto

package marabunta

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StreamRequest struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamRequest) Reset()         { *m = StreamRequest{} }
func (m *StreamRequest) String() string { return proto.CompactTextString(m) }
func (*StreamRequest) ProtoMessage()    {}
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f992b7cdbde158a, []int{0}
}

func (m *StreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamRequest.Unmarshal(m, b)
}
func (m *StreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamRequest.Marshal(b, m, deterministic)
}
func (m *StreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamRequest.Merge(m, src)
}
func (m *StreamRequest) XXX_Size() int {
	return xxx_messageInfo_StreamRequest.Size(m)
}
func (m *StreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamRequest proto.InternalMessageInfo

func (m *StreamRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type StreamResponse struct {
	// Types that are valid to be assigned to Event:
	//	*StreamResponse_EExec
	//	*StreamResponse_EPing
	//	*StreamResponse_EPulse
	//	*StreamResponse_EStatus
	Event                isStreamResponse_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *StreamResponse) Reset()         { *m = StreamResponse{} }
func (m *StreamResponse) String() string { return proto.CompactTextString(m) }
func (*StreamResponse) ProtoMessage()    {}
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f992b7cdbde158a, []int{1}
}

func (m *StreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamResponse.Unmarshal(m, b)
}
func (m *StreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamResponse.Marshal(b, m, deterministic)
}
func (m *StreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamResponse.Merge(m, src)
}
func (m *StreamResponse) XXX_Size() int {
	return xxx_messageInfo_StreamResponse.Size(m)
}
func (m *StreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamResponse proto.InternalMessageInfo

type isStreamResponse_Event interface {
	isStreamResponse_Event()
}

type StreamResponse_EExec struct {
	EExec *StreamResponse_Exec `protobuf:"bytes,1,opt,name=e_exec,json=eExec,proto3,oneof"`
}

type StreamResponse_EPing struct {
	EPing *StreamResponse_Ping `protobuf:"bytes,2,opt,name=e_ping,json=ePing,proto3,oneof"`
}

type StreamResponse_EPulse struct {
	EPulse *StreamResponse_Pulse `protobuf:"bytes,3,opt,name=e_pulse,json=ePulse,proto3,oneof"`
}

type StreamResponse_EStatus struct {
	EStatus *StreamResponse_Status `protobuf:"bytes,4,opt,name=e_status,json=eStatus,proto3,oneof"`
}

func (*StreamResponse_EExec) isStreamResponse_Event() {}

func (*StreamResponse_EPing) isStreamResponse_Event() {}

func (*StreamResponse_EPulse) isStreamResponse_Event() {}

func (*StreamResponse_EStatus) isStreamResponse_Event() {}

func (m *StreamResponse) GetEvent() isStreamResponse_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *StreamResponse) GetEExec() *StreamResponse_Exec {
	if x, ok := m.GetEvent().(*StreamResponse_EExec); ok {
		return x.EExec
	}
	return nil
}

func (m *StreamResponse) GetEPing() *StreamResponse_Ping {
	if x, ok := m.GetEvent().(*StreamResponse_EPing); ok {
		return x.EPing
	}
	return nil
}

func (m *StreamResponse) GetEPulse() *StreamResponse_Pulse {
	if x, ok := m.GetEvent().(*StreamResponse_EPulse); ok {
		return x.EPulse
	}
	return nil
}

func (m *StreamResponse) GetEStatus() *StreamResponse_Status {
	if x, ok := m.GetEvent().(*StreamResponse_EStatus); ok {
		return x.EStatus
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*StreamResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _StreamResponse_OneofMarshaler, _StreamResponse_OneofUnmarshaler, _StreamResponse_OneofSizer, []interface{}{
		(*StreamResponse_EExec)(nil),
		(*StreamResponse_EPing)(nil),
		(*StreamResponse_EPulse)(nil),
		(*StreamResponse_EStatus)(nil),
	}
}

func _StreamResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*StreamResponse)
	// event
	switch x := m.Event.(type) {
	case *StreamResponse_EExec:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.EExec); err != nil {
			return err
		}
	case *StreamResponse_EPing:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.EPing); err != nil {
			return err
		}
	case *StreamResponse_EPulse:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.EPulse); err != nil {
			return err
		}
	case *StreamResponse_EStatus:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.EStatus); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("StreamResponse.Event has unexpected type %T", x)
	}
	return nil
}

func _StreamResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*StreamResponse)
	switch tag {
	case 1: // event.e_exec
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(StreamResponse_Exec)
		err := b.DecodeMessage(msg)
		m.Event = &StreamResponse_EExec{msg}
		return true, err
	case 2: // event.e_ping
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(StreamResponse_Ping)
		err := b.DecodeMessage(msg)
		m.Event = &StreamResponse_EPing{msg}
		return true, err
	case 3: // event.e_pulse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(StreamResponse_Pulse)
		err := b.DecodeMessage(msg)
		m.Event = &StreamResponse_EPulse{msg}
		return true, err
	case 4: // event.e_status
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(StreamResponse_Status)
		err := b.DecodeMessage(msg)
		m.Event = &StreamResponse_EStatus{msg}
		return true, err
	default:
		return false, nil
	}
}

func _StreamResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*StreamResponse)
	// event
	switch x := m.Event.(type) {
	case *StreamResponse_EExec:
		s := proto.Size(x.EExec)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StreamResponse_EPing:
		s := proto.Size(x.EPing)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StreamResponse_EPulse:
		s := proto.Size(x.EPulse)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StreamResponse_EStatus:
		s := proto.Size(x.EStatus)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type StreamResponse_Exec struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamResponse_Exec) Reset()         { *m = StreamResponse_Exec{} }
func (m *StreamResponse_Exec) String() string { return proto.CompactTextString(m) }
func (*StreamResponse_Exec) ProtoMessage()    {}
func (*StreamResponse_Exec) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f992b7cdbde158a, []int{1, 0}
}

func (m *StreamResponse_Exec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamResponse_Exec.Unmarshal(m, b)
}
func (m *StreamResponse_Exec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamResponse_Exec.Marshal(b, m, deterministic)
}
func (m *StreamResponse_Exec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamResponse_Exec.Merge(m, src)
}
func (m *StreamResponse_Exec) XXX_Size() int {
	return xxx_messageInfo_StreamResponse_Exec.Size(m)
}
func (m *StreamResponse_Exec) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamResponse_Exec.DiscardUnknown(m)
}

var xxx_messageInfo_StreamResponse_Exec proto.InternalMessageInfo

func (m *StreamResponse_Exec) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type StreamResponse_Ping struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamResponse_Ping) Reset()         { *m = StreamResponse_Ping{} }
func (m *StreamResponse_Ping) String() string { return proto.CompactTextString(m) }
func (*StreamResponse_Ping) ProtoMessage()    {}
func (*StreamResponse_Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f992b7cdbde158a, []int{1, 1}
}

func (m *StreamResponse_Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamResponse_Ping.Unmarshal(m, b)
}
func (m *StreamResponse_Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamResponse_Ping.Marshal(b, m, deterministic)
}
func (m *StreamResponse_Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamResponse_Ping.Merge(m, src)
}
func (m *StreamResponse_Ping) XXX_Size() int {
	return xxx_messageInfo_StreamResponse_Ping.Size(m)
}
func (m *StreamResponse_Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamResponse_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_StreamResponse_Ping proto.InternalMessageInfo

func (m *StreamResponse_Ping) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type StreamResponse_Pulse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamResponse_Pulse) Reset()         { *m = StreamResponse_Pulse{} }
func (m *StreamResponse_Pulse) String() string { return proto.CompactTextString(m) }
func (*StreamResponse_Pulse) ProtoMessage()    {}
func (*StreamResponse_Pulse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f992b7cdbde158a, []int{1, 2}
}

func (m *StreamResponse_Pulse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamResponse_Pulse.Unmarshal(m, b)
}
func (m *StreamResponse_Pulse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamResponse_Pulse.Marshal(b, m, deterministic)
}
func (m *StreamResponse_Pulse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamResponse_Pulse.Merge(m, src)
}
func (m *StreamResponse_Pulse) XXX_Size() int {
	return xxx_messageInfo_StreamResponse_Pulse.Size(m)
}
func (m *StreamResponse_Pulse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamResponse_Pulse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamResponse_Pulse proto.InternalMessageInfo

func (m *StreamResponse_Pulse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type StreamResponse_Status struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamResponse_Status) Reset()         { *m = StreamResponse_Status{} }
func (m *StreamResponse_Status) String() string { return proto.CompactTextString(m) }
func (*StreamResponse_Status) ProtoMessage()    {}
func (*StreamResponse_Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f992b7cdbde158a, []int{1, 3}
}

func (m *StreamResponse_Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamResponse_Status.Unmarshal(m, b)
}
func (m *StreamResponse_Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamResponse_Status.Marshal(b, m, deterministic)
}
func (m *StreamResponse_Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamResponse_Status.Merge(m, src)
}
func (m *StreamResponse_Status) XXX_Size() int {
	return xxx_messageInfo_StreamResponse_Status.Size(m)
}
func (m *StreamResponse_Status) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamResponse_Status.DiscardUnknown(m)
}

var xxx_messageInfo_StreamResponse_Status proto.InternalMessageInfo

func (m *StreamResponse_Status) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type RegisterRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f992b7cdbde158a, []int{2}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RegisterResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f992b7cdbde158a, []int{3}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type UpdateRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f992b7cdbde158a, []int{4}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpdateResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f992b7cdbde158a, []int{5}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*StreamRequest)(nil), "marabunta.StreamRequest")
	proto.RegisterType((*StreamResponse)(nil), "marabunta.StreamResponse")
	proto.RegisterType((*StreamResponse_Exec)(nil), "marabunta.StreamResponse.Exec")
	proto.RegisterType((*StreamResponse_Ping)(nil), "marabunta.StreamResponse.Ping")
	proto.RegisterType((*StreamResponse_Pulse)(nil), "marabunta.StreamResponse.Pulse")
	proto.RegisterType((*StreamResponse_Status)(nil), "marabunta.StreamResponse.Status")
	proto.RegisterType((*RegisterRequest)(nil), "marabunta.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "marabunta.RegisterResponse")
	proto.RegisterType((*UpdateRequest)(nil), "marabunta.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "marabunta.UpdateResponse")
}

func init() { proto.RegisterFile("marabunta.proto", fileDescriptor_3f992b7cdbde158a) }

var fileDescriptor_3f992b7cdbde158a = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0x9b, 0xb4, 0x4d, 0xdb, 0x79, 0xe9, 0x1f, 0xf6, 0x94, 0xe6, 0x05, 0xad, 0x11, 0xa1,
	0xa7, 0x22, 0xf5, 0x20, 0x08, 0x3d, 0xa8, 0x08, 0xbd, 0x08, 0xb2, 0xc5, 0x73, 0xd9, 0xd6, 0x21,
	0x94, 0x9a, 0x4d, 0xcc, 0x6e, 0xa4, 0x9f, 0xd3, 0x6f, 0xe2, 0x37, 0x90, 0x9d, 0x34, 0xd6, 0x98,
	0xb6, 0xde, 0x1e, 0x32, 0xbf, 0x67, 0xe6, 0x99, 0x59, 0x02, 0xdd, 0x50, 0x24, 0x62, 0x91, 0x4a,
	0x2d, 0x46, 0x71, 0x12, 0xe9, 0x88, 0xb5, 0xbe, 0x3f, 0xf8, 0x67, 0xd0, 0x9e, 0xe9, 0x04, 0x45,
	0xc8, 0xf1, 0x2d, 0x45, 0xa5, 0x59, 0x0f, 0xaa, 0xa1, 0x0a, 0x5c, 0x6b, 0x60, 0x0d, 0x5b, 0xdc,
	0x48, 0xff, 0xd3, 0x86, 0x4e, 0xce, 0xa8, 0x38, 0x92, 0x0a, 0xd9, 0x35, 0x38, 0x38, 0xc7, 0x0d,
	0x2e, 0x89, 0xfb, 0x37, 0x3e, 0x19, 0xed, 0x46, 0x14, 0xd1, 0xd1, 0xc3, 0x06, 0x97, 0xd3, 0x0a,
	0xaf, 0xa3, 0x11, 0x99, 0x31, 0x5e, 0xc9, 0xc0, 0xb5, 0xff, 0x32, 0x3e, 0xad, 0x64, 0x40, 0x46,
	0x23, 0xd8, 0x0d, 0x34, 0x70, 0x1e, 0xa7, 0xaf, 0x0a, 0xdd, 0x2a, 0x39, 0x4f, 0x8f, 0x38, 0x0d,
	0x36, 0xad, 0x70, 0x07, 0x49, 0xb1, 0x09, 0x34, 0x71, 0xae, 0xb4, 0xd0, 0xa9, 0x72, 0x6b, 0x64,
	0x1e, 0x1c, 0x36, 0xcf, 0x88, 0x9b, 0x56, 0x78, 0x03, 0x33, 0xe9, 0xb9, 0x50, 0xa3, 0xec, 0xa5,
	0xcb, 0x98, 0x0a, 0x85, 0x2b, 0x57, 0xfa, 0x50, 0xcf, 0x66, 0x97, 0x4b, 0x1e, 0x38, 0x59, 0xe3,
	0x72, 0xed, 0xae, 0x01, 0x75, 0x7c, 0x47, 0xa9, 0xfd, 0x0b, 0xe8, 0x72, 0x0c, 0x56, 0x4a, 0x63,
	0x92, 0x3f, 0x0c, 0x83, 0x9a, 0x14, 0x21, 0x6e, 0x71, 0xd2, 0xbe, 0x0f, 0xbd, 0x1d, 0xb6, 0x7d,
	0x9b, 0x0e, 0xd8, 0xd1, 0x9a, 0xa8, 0x26, 0xb7, 0xa3, 0xb5, 0x7f, 0x0e, 0xed, 0xe7, 0xf8, 0x45,
	0x68, 0x3c, 0xd6, 0x68, 0x00, 0x9d, 0x1c, 0xda, 0xdf, 0x66, 0xfc, 0x61, 0x41, 0xeb, 0x31, 0x3f,
	0x1a, 0xbb, 0x35, 0x4b, 0x98, 0xbb, 0x31, 0x77, 0xcf, 0x29, 0x69, 0x8e, 0xd7, 0x3f, 0x78, 0xe4,
	0xa1, 0x75, 0x69, 0xb1, 0x7b, 0x68, 0xe6, 0xd9, 0x99, 0xf7, 0x03, 0xfd, 0xb5, 0xb7, 0xf7, 0x7f,
	0x6f, 0x6d, 0x9b, 0x72, 0x02, 0x4e, 0x96, 0xbb, 0x90, 0xa3, 0xb0, 0x6f, 0x21, 0x47, 0x71, 0xc9,
	0x85, 0x43, 0xff, 0xc3, 0xd5, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5f, 0xc7, 0x88, 0x80, 0x22,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MarabuntaClient is the client API for Marabunta service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MarabuntaClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (Marabunta_StreamClient, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
}

type marabuntaClient struct {
	cc *grpc.ClientConn
}

func NewMarabuntaClient(cc *grpc.ClientConn) MarabuntaClient {
	return &marabuntaClient{cc}
}

func (c *marabuntaClient) Stream(ctx context.Context, opts ...grpc.CallOption) (Marabunta_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Marabunta_serviceDesc.Streams[0], "/marabunta.Marabunta/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &marabuntaStreamClient{stream}
	return x, nil
}

type Marabunta_StreamClient interface {
	Send(*StreamRequest) error
	Recv() (*StreamResponse, error)
	grpc.ClientStream
}

type marabuntaStreamClient struct {
	grpc.ClientStream
}

func (x *marabuntaStreamClient) Send(m *StreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *marabuntaStreamClient) Recv() (*StreamResponse, error) {
	m := new(StreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *marabuntaClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/marabunta.Marabunta/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marabuntaClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/marabunta.Marabunta/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarabuntaServer is the server API for Marabunta service.
type MarabuntaServer interface {
	Stream(Marabunta_StreamServer) error
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
}

func RegisterMarabuntaServer(s *grpc.Server, srv MarabuntaServer) {
	s.RegisterService(&_Marabunta_serviceDesc, srv)
}

func _Marabunta_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MarabuntaServer).Stream(&marabuntaStreamServer{stream})
}

type Marabunta_StreamServer interface {
	Send(*StreamResponse) error
	Recv() (*StreamRequest, error)
	grpc.ServerStream
}

type marabuntaStreamServer struct {
	grpc.ServerStream
}

func (x *marabuntaStreamServer) Send(m *StreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *marabuntaStreamServer) Recv() (*StreamRequest, error) {
	m := new(StreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Marabunta_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarabuntaServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/marabunta.Marabunta/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarabuntaServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marabunta_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarabuntaServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/marabunta.Marabunta/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarabuntaServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Marabunta_serviceDesc = grpc.ServiceDesc{
	ServiceName: "marabunta.Marabunta",
	HandlerType: (*MarabuntaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Marabunta_Register_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Marabunta_Update_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Marabunta_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "marabunta.proto",
}
